In [2]:
import pandas as pd
import nltk
from nltk import word_tokenize

/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/_libs/__init__.py:4: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/__init__.py:26: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (hashtable as _hashtable,
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/dtypes/common.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/util/hashing.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import hashing, tslib
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/indexes/base.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, index as libindex, tslib as libts,
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/tseries/offsets.py:21: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.tslibs.offsets as liboffsets
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/ops.py:16: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as libalgos, ops as libops
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/indexes/interval.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs.interval import (
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/internals.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import internals as libinternals
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/sparse/array.py:33: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.sparse as splib
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/window.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.window as _window
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/groupby/groupby.py:68: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import (lib, reduction,
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/core/reshape/reshape.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos as _algos, reshape as _reshape
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/io/parsers.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  import pandas._libs.parsers as parsers
/home/vibha/miniconda2/lib/python2.7/site-packages/pandas/io/pytables.py:50: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from pandas._libs import algos, lib, writers as libwriters
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/utils/__init__.py:12: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .murmurhash import murmurhash3_32
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/feature_extraction/hashing.py:14: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._hashing import transform as _hashing_transform
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/utils/extmath.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._logistic_sigmoid import _log_logistic_sigmoid
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/utils/extmath.py:25: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sparsefuncs_fast import csr_row_norms
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/utils/random.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._random import sample_without_replacement
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/datasets/svmlight_format.py:32: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._svmlight_format import _load_svmlight_file
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/svm/base.py:8: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import libsvm, liblinear
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/svm/base.py:9: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import libsvm_sparse
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/linear_model/base.py:35: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ..utils.seq_dataset import ArrayDataset, CSRDataset
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/linear_model/least_angle.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ..utils import arrayfuncs, as_float_array, check_X_y, deprecated
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/metrics/cluster/supervised.py:25: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .expected_mutual_info_fast import expected_mutual_information
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/metrics/pairwise.py:31: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/linear_model/coordinate_descent.py:30: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import cd_fast
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/linear_model/__init__.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sgd_fast import Hinge, Log, ModifiedHuber, SquaredLoss, Huber
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/linear_model/sag.py:12: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sag_fast import sag
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/neighbors/__init__.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ball_tree import BallTree
/home/vibha/miniconda2/lib/python2.7/site-packages/sklearn/neighbors/__init__.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .kd_tree import KDTree

In [43]:
sen="the food was best but the serving was worst"

In [44]:
import re
sen = [re.sub(r"[^a-zA-Z0-9]+", ' ', k) for k in sen.split("\n")]
print(sen)
sen2=sen

['the food was best but the serving was worst']

In [45]:
# import csv 
  
# # csv file name 
# filename = "parser_sentences3.csv"
  
# # initializing the titles and rows list 
# fields = [] 
# rows = [] 
  
# # reading csv file 
# with open(filename, 'r') as csvfile: 
#     # creating a csv reader object 
#     csvreader = csv.reader(csvfile) 
      
#     # extracting field names through first row 
#     fields = csvreader.next() 
#     rows.append(fields)
  
#     # extracting each data row one by one 
#     for row in csvreader: 
#         #print row
#         rows.append(row)

In [46]:
sen=word_tokenize(sen[0])

In [47]:
# for i in rows:
#     print i
#     sen=word_tokenize(i)
#     print sen

In [48]:
sen

['the', 'food', 'was', 'best', 'but', 'the', 'serving', 'was', 'worst']

In [49]:
df=pd.DataFrame(sen,columns=['word'])
df['stopword']=0
df['pos_tag']=''

In [50]:
from nltk.corpus import stopwords
a=set(stopwords.words('english'))

In [51]:
df['word_len']=0

In [52]:
df

      word  stopword pos_tag  word_len
0      the         0                 0
1     food         0                 0
2      was         0                 0
3     best         0                 0
4      but         0                 0
5      the         0                 0
6  serving         0                 0
7      was         0                 0
8    worst         0                 0

In [53]:
for i in range(0,len(df)):
    if (df['word'][i]) in a:
        df['stopword'][i]=1
        
        
    else:
        df['stopword'][i]=0
        
        
    if(len(df['word'][i])>3):
        df['word_len'][i]=1
    else:
        df['word_len'][i]=0

/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

In [54]:
df

      word  stopword pos_tag  word_len
0      the         1                 0
1     food         0                 1
2      was         1                 0
3     best         0                 1
4      but         1                 0
5      the         1                 0
6  serving         0                 1
7      was         1                 0
8    worst         0                 1

In [132]:
post_tag=nltk.pos_tag(sen
                     )

In [56]:
post_tag[0][1]

'DT'

In [57]:
df['pos_tag']=post_tag

In [58]:
df

      word  stopword        pos_tag  word_len
0      the         1      (the, DT)         0
1     food         0     (food, NN)         1
2      was         1     (was, VBD)         0
3     best         0    (best, RBS)         1
4      but         1      (but, CC)         0
5      the         1      (the, DT)         0
6  serving         0  (serving, NN)         1
7      was         1     (was, VBD)         0
8    worst         0    (worst, RB)         1

In [59]:
next_l=[]
k=0
for i in range(0,len(sen)-1):
    print i
    next_l.append(sen[i+1])

0
1
2
3
4
5
6
7

In [60]:
next_l.append("")

In [61]:
next_l

['food', 'was', 'best', 'but', 'the', 'serving', 'was', 'worst', '']

In [62]:
df['next_words']=""

In [63]:
df['next_words']=next_l

In [64]:
df['prev_words']=""
prev=[]

In [65]:
prev.append("")

In [66]:
for i in range(1,len(sen)):
    print i
    print sen[i]
    prev.append(sen[i-1])

1
food
2
was
3
best
4
but
5
the
6
serving
7
was
8
worst

In [67]:
prev

['', 'the', 'food', 'was', 'best', 'but', 'the', 'serving', 'was']

In [68]:
df['prev_words']=prev

In [69]:
df

      word  stopword        pos_tag  word_len next_words prev_words
0      the         1      (the, DT)         0       food
1     food         0     (food, NN)         1        was        the
2      was         1     (was, VBD)         0       best       food
3     best         0    (best, RBS)         1        but        was
4      but         1      (but, CC)         0        the       best
5      the         1      (the, DT)         0    serving        but
6  serving         0  (serving, NN)         1        was        the
7      was         1     (was, VBD)         0      worst    serving
8    worst         0    (worst, RB)         1                   was

In [70]:
df['pre_word_tag']=""
df['post_word_tag']=""
print sen

['the', 'food', 'was', 'best', 'but', 'the', 'serving', 'was', 'worst']

In [71]:
import os
a=os.popen("echo '"+sen2[0]+"' > ~/stanford-parser-2012-11-12/stanfordtemp.txt")
parser_out = os.popen("~/stanford-parser-2012-11-12/lexparser.sh ~/stanford-parser-2012-11-12/stanfordtemp.txt")
print parser_out
for relation in parser_out:
    print(relation)

<open file '~/stanford-parser-2012-11-12/lexparser.sh ~/stanford-parser-2012-11-12/stanfordtemp.txt', mode 'r' at 0x7f79283f64b0>
(ROOT

  (S

    (NP (DT the) (NN food))

    (VP (VBD was)

      (ADJP (JJS best))

      (SBAR (CC but)

        (S

          (NP (DT the) (NN serving))

          (VP (VBD was)

            (ADJP (JJS worst))))))))



det(food-2, the-1)

nsubj(best-4, food-2)

cop(best-4, was-3)

root(ROOT-0, best-4)

cc(worst-9, but-5)

det(serving-7, the-6)

nsubj(worst-9, serving-7)

cop(worst-9, was-8)

ccomp(best-4, worst-9)

In [74]:
from nltk.tree import Tree

examples = [ '(ROOT (S     (NP (DT the) (NN food))    (VP (VBD was) (ADJP (JJS best)) (SBAR (CC but) (S  (NP (DT the) (NN serving)) (VP (VBD was)       (ADJP (JJS worst))))))))']
head_word=[]

def find_noun_phrases(tree):
    return [subtree for subtree in tree.subtrees(lambda t: t.label()=='NP')]

def find_head_of_np(np):
    noun_tags = ['NN', 'NNS', 'NNP', 'NNPS']
    top_level_trees = [np[i] for i in range(len(np)) if type(np[i]) is Tree]
    ## search for a top-level noun
    top_level_nouns = [t for t in top_level_trees if t.label() in noun_tags]
    if len(top_level_nouns) > 0:
        ## if you find some, pick the rightmost one, just 'cause
        return top_level_nouns[-1][0]
    else:
        ## search for a top-level np
        top_level_nps = [t for t in top_level_trees if t.label()=='NP']
        if len(top_level_nps) > 0:
            ## if you find some, pick the head of the rightmost one, just 'cause
            return find_head_of_np(top_level_nps[-1])
        else:
            ## search for any noun
            nouns = [p[0] for p in np.pos() if p[1] in noun_tags]
            if len(nouns) > 0:
                ## if you find some, pick the rightmost one, just 'cause
                return nouns[-1]
            else:
                ## return the rightmost word, just 'cause
                return np.leaves()[-1]

for example in examples:
    tree = Tree.fromstring(example)
    for np in find_noun_phrases(tree):
       
        print " ".join(np.leaves())
        head = find_head_of_np(np)
        
        if head not in head_word:
            
            head_word.append(head)

the food
the serving

In [75]:
head_word

['food', 'serving']

In [76]:
post_tag[0]

('the', 'DT')

In [77]:
df['head_word']=0
pos_pre=[]
pos_pre.append("")
pos_post=[]
for i in range(0,len(post_tag)-1):
    pos_post.append(post_tag[i+1])
pos_post.append("")

for i in range(1,len(post_tag)):
    pos_pre.append(post_tag[i-1])

df['pre_word_tag']=pos_pre
df['post_word_tag']=pos_post

In [78]:

for i in range(0,len(df)):
   
        

    if (df['word'][i]) in head_word:
        print df['word'][i]
        df['head_word'][i]=1
    else:
        df['head_word'][i]=0

/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

food
serving

In [79]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word
0,the,1,"(the, DT)",0,food,,,"(food, NN)",0
1,food,0,"(food, NN)",1,was,the,"(the, DT)","(was, VBD)",1
2,was,1,"(was, VBD)",0,best,food,"(food, NN)","(best, RBS)",0
3,best,0,"(best, RBS)",1,but,was,"(was, VBD)","(but, CC)",0
4,but,1,"(but, CC)",0,the,best,"(best, RBS)","(the, DT)",0
5,the,1,"(the, DT)",0,serving,but,"(but, CC)","(serving, NN)",0
6,serving,0,"(serving, NN)",1,was,the,"(the, DT)","(was, VBD)",1
7,was,1,"(was, VBD)",0,worst,serving,"(serving, NN)","(worst, RB)",0
8,worst,0,"(worst, RB)",1,,was,"(was, VBD)",,0

In [112]:
t1="she is serving food in the restaurant"
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
  
    print(lemmatizer.lemmatize('worst','a'))

bad
bad
bad
bad
bad
bad
bad
bad
bad

In [113]:
from nltk.corpus import wordnet

morphy_tag = {'NN':wordnet.NOUN,'JJS':wordnet.ADJ,'VBD':wordnet.VERB,'RB':wordnet.ADJ,'VBG':wordnet.VERB}

In [114]:
morphy_tag

{'JJS': u'a', 'NN': u'n', 'RB': u'a', 'VBD': u'v', 'VBG': u'v'}

In [115]:
#t1="she is serving food in the restaurant"
df['lematized_words']='NULL'
lema=[]
from nltk.stem import WordNetLemmatizer 
  
lemmatizer = WordNetLemmatizer() 
for i in range(0,len(sen)):
    c=post_tag[i][1]
    for name in morphy_tag.keys():
        if name == c:
            print name
            new=morphy_tag[name]
            print new
    lema.append(lemmatizer.lemmatize(post_tag[i][0],new))

NN
n
VBD
v
NN
n
VBD
v
RB
a

In [116]:
lema

['the', 'food', u'be', 'best', 'but', 'the', 'serving', u'be', u'bad']

In [117]:
df['lematized_words']=lema

In [118]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words
0,the,1,"(the, DT)",0,food,,,"(food, NN)",0,the
1,food,0,"(food, NN)",1,was,the,"(the, DT)","(was, VBD)",1,food
2,was,1,"(was, VBD)",0,best,food,"(food, NN)","(best, RBS)",0,be
3,best,0,"(best, RBS)",1,but,was,"(was, VBD)","(but, CC)",0,best
4,but,1,"(but, CC)",0,the,best,"(best, RBS)","(the, DT)",0,but
5,the,1,"(the, DT)",0,serving,but,"(but, CC)","(serving, NN)",0,the
6,serving,0,"(serving, NN)",1,was,the,"(the, DT)","(was, VBD)",1,serving
7,was,1,"(was, VBD)",0,worst,serving,"(serving, NN)","(worst, RB)",0,be
8,worst,0,"(worst, RB)",1,,was,"(was, VBD)",,0,bad

In [119]:
import re

file_to_open=open("Documents/parser_sentences3.txt", 'r')

text = ' '.join(file_to_open.readlines())
sentences = re.split(r' *[\.\?!][\'"\)\]]* *', text)

In [120]:
sentences

[' Most everything is fine with this machine: speed, capacity, build',
 "The only thing I don't understand is that the resolution of the screen isn't high enough for some pages, such as Yahoo",
 'Mail',
 'Yes, I have it on the highest available setting',
 '\n  I love the size, keyboard, the functions',
 "I don't really have a complaint",
 'It is easy to use, good quality and good price',
 'Perfect trifecta',
 'I would recommend this product',
 '\n  I love this product because it is Toshiba and its 15',
 '6"',
 'It has no camera but, I can always buy and install one easy',
 "I had a USB connect but, i can't use it because it is not compatible",
 "That's the downside for me",
 'But, I would recommend this product',
 "\n  I bought this laptop Was the worst Laptop I've ever bought",
 'I spent alot of money on this product and its been a nightmare',
 'And having to deal with the company has been a even worse nightmare',
 'I sent it to them to fix in perfect condition but for what was wrong with it',
 "They sent it back with a huge crack in it and it still didn't work",
 'And that was the fourth time ive sent it to them to get fixed',
 'Its been a year and am still waiting to see what there going to do about my laptop',
 'So if anyones looking to buy a computer or laptop you should stay far far away from any that have the name TOSHIBA on it',
 '',
 '',
 '\n  So far, a great product',
 'High price tag, however',
 'Still trying to learn how to use it',
 '\n  This laptop is a great price and has a sleek look',
 'Runs smooth and quick',
 'I wish it had a webcam though, then it would be perfect',
 '\n  HP Pavilion DV9000 Notebook PC      When I first got this computer, it really rocked',
 'But as time went on I found it almost impossible to keep the thing on-line through wi-fi',
 'Eventually the screen went blank and the computer would not turn on',
 'HP said it was out of warranty',
 "Guess I'll stay away from HP",
 '\n  Great price and computer',
 'I bought this laptop computer for my parents, they only access their facebook and e-mail accounts, see family pictures, etc',
 'They loved it',
 "It's easy to operate and it's very light (my parents are almost 60 yo, they can't carry a heavy computer while traveling)",
 "But here's something I hadn't realized before buying it: there isn't an optical drive, which means NO CDs or DVDs",
 '\n  I have loved this since i took it out of the box',
 'The battery is really long',
 'the features are great, the only thing it needs is better speakers',
 '\n  Waited on getting this computer, but it has been a great change',
 'Ease of use is just one of the benefits I love about my Mac',
 '\n  It had most of the features and all of the power that I wanted to replace my desktop machine',
 "I wasn't really as concerned about portability (it's a very large laptop) but it's not hard to move around or take on a trip which was a pleasant surprise",
 "I'm very happy with this machine",
 '\n  This MacBook is an outstanding product with great value',
 'Its ease of use and the top service from Apple- be it their phone assistance or bellying up to the genius bar- cannot be beat',
 'Suffice it to say, my MacBook Pro keeps me going with its long battery life and blazing speed',
 'It does run a little warm but that is a negligible concern',
 '\n  The image is great, and the soud is excelent',
 'i love ths notebook',
 '\n  Small and light weight',
 'Speakers too small to be of any real use',
 'Keyboard good sized and wasy to use',
 'I like it',
 '\n  This is a great machine',
 'The design is awesome, quality is unprecedented',
 "\n  This just keeps having it's hard drive replaced",
 "Acer won't replace the laptop",
 "the manufacturer's warranty only covers replacement/repair of parts",
 'This thing is a lemon',
 '\n  I love the glass touchpad',
 'Easy learning curve',
 'Also the display is exceptional',
 '\n  Very good quality and well made',
 'Great pick for portability and affordability',
 "The black model also has a very nice seamless appearance - one of the better looking notebooks I've seen",
 '\n  This computer is the ideal college companion',
 "It's software and speed enable it to do amazing things",
 '\n  It was too cheaply constructed',
 'It also gave me an introduction to Windows 8, which I hope will be discontinued it the future',
 '\n  If you need an affordable, entry-level laptop, this will fit the bill',
 'I dislike the weight and size, cubersome',
 'I dislike the quality and the placement of the speakers',
 "Overall, it's ok",
 '\n  My son and his family have a hard time financially because he is self-employed so the family had no computer of any kind, and kyle the oldest child is 12 and really need something to help him in school',
 'so we got a good deal on hsn for an ascer notebook and we bought it for him',
 'He loves it and it is easy to use and well the schools start teaching the kids early about computers so it was easy for him to get started',
 'now he mows yards so he can earn the money for the wireless internet',
 'I would recomend this acer to parents and grandparents it can really help them in school',
 '\n  the laptop was really good and it goes really fast just the way i thought it would of run',
 'i would really recommend to any person out there to get this laptop cause its really worth it',
 'and its really cheap and you wont regret buying it',
 '\n  The Notebook PC,Toshiba Qosmio is the best gift my father could have ever gotten me',
 'He gave me this PC about 3 years ago and up to this point im still sitting here using it',
 'Its still going',
 'It is in the best condition and has a really high quality',
 'This is something i would deffinately reccomend to someone',
 'You will not regret buying such a great thing like this',
 "It can't get any better",
 '\n  it is the worst computer dell ever made',
 'it is hard to fix and makes it a hassle to own one',
 'breaks easily',
 'only good thing is the graphics quality',
 "\n  It rarely works and when it does it's incredibly slow",
 'I have had to take it to the geek squad guys to get it fixed because it has had viruses 3 times and i have not even had it for more then 4 months',
 '*IF YOU ARE LOOKING FOR A GOOD LAPTOP, THIS IS NOT IT',
 '\n']

In [121]:
df['ortho_features']=''
for i in range(0,len(df)):
    if ((df['word'][i].istitle() == True) or (df['word'][i].isdigit()==True)):
        df['ortho_features'][i]=1
    else:
        df['ortho_features'][i]=0

/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [122]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features
0,the,1,"(the, DT)",0,food,,,"(food, NN)",0,the,0
1,food,0,"(food, NN)",1,was,the,"(the, DT)","(was, VBD)",1,food,0
2,was,1,"(was, VBD)",0,best,food,"(food, NN)","(best, RBS)",0,be,0
3,best,0,"(best, RBS)",1,but,was,"(was, VBD)","(but, CC)",0,best,0
4,but,1,"(but, CC)",0,the,best,"(best, RBS)","(the, DT)",0,but,0
5,the,1,"(the, DT)",0,serving,but,"(but, CC)","(serving, NN)",0,the,0
6,serving,0,"(serving, NN)",1,was,the,"(the, DT)","(was, VBD)",1,serving,0
7,was,1,"(was, VBD)",0,worst,serving,"(serving, NN)","(worst, RB)",0,be,0
8,worst,0,"(worst, RB)",1,,was,"(was, VBD)",,0,bad,0

In [123]:
df['token_freq']=''
for i in range(0,len(df)):
    df['token_freq'][i]=sen.count(df['word'][i])

/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [124]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq
0,the,1,"(the, DT)",0,food,,,"(food, NN)",0,the,0,2
1,food,0,"(food, NN)",1,was,the,"(the, DT)","(was, VBD)",1,food,0,1
2,was,1,"(was, VBD)",0,best,food,"(food, NN)","(best, RBS)",0,be,0,2
3,best,0,"(best, RBS)",1,but,was,"(was, VBD)","(but, CC)",0,best,0,1
4,but,1,"(but, CC)",0,the,best,"(best, RBS)","(the, DT)",0,but,0,1
5,the,1,"(the, DT)",0,serving,but,"(but, CC)","(serving, NN)",0,the,0,2
6,serving,0,"(serving, NN)",1,was,the,"(the, DT)","(was, VBD)",1,serving,0,1
7,was,1,"(was, VBD)",0,worst,serving,"(serving, NN)","(worst, RB)",0,be,0,2
8,worst,0,"(worst, RB)",1,,was,"(was, VBD)",,0,bad,0,1

In [133]:
post_tag

[('the', 'DT'),
 ('food', 'NN'),
 ('was', 'VBD'),
 ('best', 'RBS'),
 ('but', 'CC'),
 ('the', 'DT'),
 ('serving', 'NN'),
 ('was', 'VBD'),
 ('worst', 'RB')]

In [141]:
df['head_word_tag']=""
for i in range(0,len(post_tag)):
    
    if(post_tag[i][0] in head_word):
        df['head_word_tag'][i]=post_tag[i][1]

/home/vibha/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [142]:
df

,word,stopword,pos_tag,word_len,next_words,prev_words,pre_word_tag,post_word_tag,head_word,lematized_words,ortho_features,token_freq,head_word_tag
0,the,1,"(the, DT)",0,food,,,"(food, NN)",0,the,0,2,
1,food,0,"(food, NN)",1,was,the,"(the, DT)","(was, VBD)",1,food,0,1,NN
2,was,1,"(was, VBD)",0,best,food,"(food, NN)","(best, RBS)",0,be,0,2,
3,best,0,"(best, RBS)",1,but,was,"(was, VBD)","(but, CC)",0,best,0,1,
4,but,1,"(but, CC)",0,the,best,"(best, RBS)","(the, DT)",0,but,0,1,
5,the,1,"(the, DT)",0,serving,but,"(but, CC)","(serving, NN)",0,the,0,2,
6,serving,0,"(serving, NN)",1,was,the,"(the, DT)","(was, VBD)",1,serving,0,1,NN
7,was,1,"(was, VBD)",0,worst,serving,"(serving, NN)","(worst, RB)",0,be,0,2,
8,worst,0,"(worst, RB)",1,,was,"(was, VBD)",,0,bad,0,1,